### ISSUE TITLE
 Formats: standardize commit message body format

### ISSUE THREAD

**Issue by PierceAndy** [oss-generic/process#53]
As per @damithc's [suggestion here](https://github.com/se-edu/addressbook-level4/pull/272#issuecomment-278345886), going forward let's stick to this format for commit messages bodies:

```
{current situation}
{why it is bad}
{what is being done about it}
```

- Explain the current situation and why it is a problem (present tense)
- Explain what is being done about it (imperative mood)

e.g.

```
Parser class contains code for parsing all command types.
This makes the Parser class bloated and can be considered
a violation of the Single Responsibility Principle. The solution
is to extract code for parsing each command into a separate
*CommandParser class. However, that can result in bidirectional 
links between those classes and the Parser class because some
of the constants and utility methods in Parser class will be used
by those classes as well.

Let's extract reusable constants into a new CliSyntax class and 
utility methods into a new ParserUtil class so that such
bidirectional links can be avoided.
```

**Comment by MightyCupcakes** [comment]
Since the original commit message used in the example was modified and improved - this post aims to provide a better example while allowing some form of flexibility.

This is the first paragraph: describe current situation and give readers (that might be new to the project) of the current situation. Leave words like `currently` out as it should be implied in this paragraph.

>Parser class implements all different
command parsers as private methods within the Parser class.
Parser::parseCommand is responsible for performing an initial
parsing on the given input string and from there determine
the correct method to parse the String to.

The following paragraph is why is the current code bad/problematic.

>This causes the Parser file to become very long
containing all command parser methods and their
associated helper methods that is only utilized in that
one method itself.

The next two paragraphs is a deviation of the three paragraph standard. These paragraphs can be omitted. The aim of this paragraph is to provide readers some context before proposing the solution. This allows the author of the commit message some form of flexibility when writing his commit messages.

>The design can be improved by applying the Single Responsibility
Principle as follows: limit the Parser's responsibility to determining
which type of command is being parsed and move the responsibility
of parsing each type of command to a separate *CommandParser class.

>However, this will result in bidirectional links between these various
*CommandParser classes and the main Parser class because some
of the constants and utility methods in Parser class will be used
by the various *CommandParser classes as well.

And this is the solution (what is being done about it). As discussed, it is agreed that we try to start with `Let's do...` , `Let's extract` , `Let's remove` or any of its variants. In this example, we show the flexibility given to the author to include some words before the `Lets...` to optionally link to the paragraphs above.

>As a step toward the design proposed above, let's extract reusable
constants into a new CliSyntax class and utility methods into a new
ParserUtil class to prevent bidirectional dependencies between
the Parser class and the proposed *CommandPraser classes.

**Comment by damithc** [comment]
@MightyCupcakes sorry my PR crossed your post. I did not use this commit message example in the PR.
